### PR TITLE
Let CMake find shared Fortran runtime library

### PR DESCRIPTION
**Pull request by bkmgit**
Do not make a copy of the library

Needed to address https://github.com/lfortran/lfortran/issues/2096

### CODE REVIEW

**Comment by certik** [comment]
@Pranavchiku can you review this?

**Comment by Pranavchiku** [comment]
On it.

**Review by Pranavchiku — APPROVED** [review]
This looks good! I tested it locally, it works.

**Review by certik — APPROVED** [review]
I think this seems cleaner from my perspective as well.

**Pull request merged**
